In [70]:
import torch
torch.__version__

'2.5.1+cu124'

In [71]:
scalar = torch.tensor(7) # create scalar
scalar # returns scalar class instance

tensor(7)

In [72]:
scalar.ndim # returns the dimensions of scalar

0

In [73]:
scalar.item() # get the python number within a tensor (only works with one-element tensor)

7

In [74]:
vector = torch.tensor([7,7]) # create vector
vector # returns vector class instance

tensor([7, 7])

In [75]:
vector.ndim # returns dimensions of vector

1

In [76]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix # returns matrix class instance

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
matrix.ndim # returns dimensions of matrix

2

In [78]:
matrix.shape # returns shape of matrix

torch.Size([2, 2])

In [79]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [2, 4, 5]]])
tensor # returns tensor class instance

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [80]:
tensor.ndim # returns dimensions of tensor

3

In [81]:
tensor.shape # returns shape of tensor

torch.Size([1, 3, 3])

In [82]:
random_tensor = torch.rand(size = (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9745, 0.6969, 0.3858, 0.6210],
         [0.6060, 0.4458, 0.3386, 0.7542],
         [0.6502, 0.0029, 0.5049, 0.3748]]),
 torch.float32)

In [83]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [84]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [85]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [86]:
zero_to_ten_deprecated = torch.range(0, 10)

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_1542313/1052060013.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype